risky: true

preset: laravel

enabled:
  - strict
  - unalign_double_arrow
  - phpdoc_order

disabled:
  - short_array_syntax

finder:
  exclude:
    - "public"
    - "resources"
    - "tests"
  name:
    - "*.php"
